'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property EjecucionManual() As String
            Get
                Return CType(Me("EjecucionManual"),String)
            End Get
            Set
                Me("EjecucionManual") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Respuestas_X_Pantalla() As String
            Get
                Return CType(Me("Respuestas_X_Pantalla"),String)
            End Get
            Set
                Me("Respuestas_X_Pantalla") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DSN=micros;Uid=micros;Pwd=DMICMSR40;")>  _
        Public Property strConexionODBC() As String
            Get
                Return CType(Me("strConexionODBC"),String)
            End Get
            Set
                Me("strConexionODBC") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost/GTIntegration/ServiciosWeb/wsGenerarPlano.asmx")>  _
        Public ReadOnly Property slnMonoProceso_wsGenerarPlano_wsGenerarPlano() As String
            Get
                Return CType(Me("slnMonoProceso_wsGenerarPlano_wsGenerarPlano"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.75.65.2/WSUNOEE/WSUNOEE.asmx")>  _
        Public ReadOnly Property slnMonoProceso_wsUnoEE_WSUNOEE() As String
            Get
                Return CType(Me("slnMonoProceso_wsUnoEE_WSUNOEE"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("server = ERPTEST; User Id=gentrerp; pwd = gentrerp; Unicode = true;")>  _
        Public Property strConexionOracle() As String
            Get
                Return CType(Me("strConexionOracle"),String)
            End Get
            Set
                Me("strConexionOracle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\Reynel\Desktop\Debug\CCC\XML\")>  _
        Public Property ruta_xml() As String
            Get
                Return CType(Me("ruta_xml"),String)
            End Get
            Set
                Me("ruta_xml") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("admin_camaracali")>  _
        Public Property usuario_Certicamara() As String
            Get
                Return CType(Me("usuario_Certicamara"),String)
            End Get
            Set
                Me("usuario_Certicamara") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("camaracali001")>  _
        Public Property pass_Certicamara() As String
            Get
                Return CType(Me("pass_Certicamara"),String)
            End Get
            Set
                Me("pass_Certicamara") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\Reynel\Desktop\Debug\CCC\XML\")>  _
        Public Property ruta_xml_final() As String
            Get
                Return CType(Me("ruta_xml_final"),String)
            End Get
            Set
                Me("ruta_xml_final") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.0.1.29/GTIntegration/ServiciosWeb/wsGenerarPlano.asmx")>  _
        Public ReadOnly Property slnMonoProceso_wsGT_wsGenerarPlano() As String
            Get
                Return CType(Me("slnMonoProceso_wsGT_wsGenerarPlano"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("server = ERPTEST; User Id=gentrerp; pwd = gentrerp; Unicode = true;Connection Lif"& _ 
            "etime=30;")>  _
        Public Property strConexionIntermedia() As String
            Get
                Return CType(Me("strConexionIntermedia"),String)
            End Get
            Set
                Me("strConexionIntermedia") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=siesa.generictransfer.com,1434;Initial Catalog=GTintegrationCCC;User "& _ 
            "ID=admincali;Password=4217;Integrated Security=False;")>  _
        Public Property strConexionGT() As String
            Get
                Return CType(Me("strConexionGT"),String)
            End Get
            Set
                Me("strConexionGT") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.slnMonoProceso.My.MySettings
            Get
                Return Global.slnMonoProceso.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
