'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace wsAdq
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
        "a.com/")>  _
    Partial Public Class ExcepcionServiciosTecnica
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private campoField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property campo() As String
            Get
                Return Me.campoField
            End Get
            Set
                Me.campoField = value
                Me.RaisePropertyChanged("campo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("mensaje")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
        "a.com/")>  _
    Partial Public Class camposDinamicosWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nombreCampoField As String
        
        Private valorField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property nombreCampo() As String
            Get
                Return Me.nombreCampoField
            End Get
            Set
                Me.nombreCampoField = value
                Me.RaisePropertyChanged("nombreCampo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("valor", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property valor() As String()
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("valor")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
        "a.com/")>  _
    Partial Public Class adquirienteActualizaWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private apellidosField As String
        
        Private ciudadExtranjeraField As String
        
        Private codigoCiudadField As String
        
        Private codigoDepartamentoField As String
        
        Private codigoPaisField As String
        
        Private direccionField As String
        
        Private emailPrincipalField As String
        
        Private emailSecundariosField() As String
        
        Private faxField As String
        
        Private nombreField As String
        
        Private razonSocialField As String
        
        Private telefonoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property apellidos() As String
            Get
                Return Me.apellidosField
            End Get
            Set
                Me.apellidosField = value
                Me.RaisePropertyChanged("apellidos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property ciudadExtranjera() As String
            Get
                Return Me.ciudadExtranjeraField
            End Get
            Set
                Me.ciudadExtranjeraField = value
                Me.RaisePropertyChanged("ciudadExtranjera")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property codigoCiudad() As String
            Get
                Return Me.codigoCiudadField
            End Get
            Set
                Me.codigoCiudadField = value
                Me.RaisePropertyChanged("codigoCiudad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property codigoDepartamento() As String
            Get
                Return Me.codigoDepartamentoField
            End Get
            Set
                Me.codigoDepartamentoField = value
                Me.RaisePropertyChanged("codigoDepartamento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property codigoPais() As String
            Get
                Return Me.codigoPaisField
            End Get
            Set
                Me.codigoPaisField = value
                Me.RaisePropertyChanged("codigoPais")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
                Me.RaisePropertyChanged("direccion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property emailPrincipal() As String
            Get
                Return Me.emailPrincipalField
            End Get
            Set
                Me.emailPrincipalField = value
                Me.RaisePropertyChanged("emailPrincipal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("emailSecundarios", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=7)>  _
        Public Property emailSecundarios() As String()
            Get
                Return Me.emailSecundariosField
            End Get
            Set
                Me.emailSecundariosField = value
                Me.RaisePropertyChanged("emailSecundarios")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property fax() As String
            Get
                Return Me.faxField
            End Get
            Set
                Me.faxField = value
                Me.RaisePropertyChanged("fax")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property razonSocial() As String
            Get
                Return Me.razonSocialField
            End Get
            Set
                Me.razonSocialField = value
                Me.RaisePropertyChanged("razonSocial")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property telefono() As String
            Get
                Return Me.telefonoField
            End Get
            Set
                Me.telefonoField = value
                Me.RaisePropertyChanged("telefono")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
        "a.com/")>  _
    Partial Public Class identificacionAdquirienteWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoDianField As Integer
        
        Private codigoDianFieldSpecified As Boolean
        
        Private digitoDeVerificacionField As Integer
        
        Private digitoDeVerificacionFieldSpecified As Boolean
        
        Private numeroIdentificacionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codigoDian() As Integer
            Get
                Return Me.codigoDianField
            End Get
            Set
                Me.codigoDianField = value
                Me.RaisePropertyChanged("codigoDian")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property codigoDianSpecified() As Boolean
            Get
                Return Me.codigoDianFieldSpecified
            End Get
            Set
                Me.codigoDianFieldSpecified = value
                Me.RaisePropertyChanged("codigoDianSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property digitoDeVerificacion() As Integer
            Get
                Return Me.digitoDeVerificacionField
            End Get
            Set
                Me.digitoDeVerificacionField = value
                Me.RaisePropertyChanged("digitoDeVerificacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property digitoDeVerificacionSpecified() As Boolean
            Get
                Return Me.digitoDeVerificacionFieldSpecified
            End Get
            Set
                Me.digitoDeVerificacionFieldSpecified = value
                Me.RaisePropertyChanged("digitoDeVerificacionSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property numeroIdentificacion() As String
            Get
                Return Me.numeroIdentificacionField
            End Get
            Set
                Me.numeroIdentificacionField = value
                Me.RaisePropertyChanged("numeroIdentificacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
        "a.com/")>  _
    Partial Public Class ExcepcionServiciosNegocio
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private campoField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property campo() As String
            Get
                Return Me.campoField
            End Get
            Set
                Me.campoField = value
                Me.RaisePropertyChanged("campo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("mensaje")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
        "a.com/", ConfigurationName:="wsAdq.IServiciosAdquiriente")>  _
    Public Interface IServiciosAdquiriente
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
            "a.com/IServiciosAdquiriente/actualizarAdquirienteACliente", ReplyAction:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
            "a.com/IServiciosAdquiriente/actualizarAdquirienteAClienteResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(wsAdq.ExcepcionServiciosTecnica), Action:="http://www.w3.org/2005/08/addressing/soap/fault", Name:="ExcepcionServiciosTecnica"),  _
         System.ServiceModel.FaultContractAttribute(GetType(wsAdq.ExcepcionServiciosNegocio), Action:="http://www.w3.org/2005/08/addressing/soap/fault", Name:="ExcepcionServiciosNegocio"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function actualizarAdquirienteACliente(ByVal request As wsAdq.actualizarAdquirienteACliente) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> wsAdq.actualizarAdquirienteAClienteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
            "a.com/IServiciosAdquiriente/actualizarAdquirienteACliente", ReplyAction:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
            "a.com/IServiciosAdquiriente/actualizarAdquirienteAClienteResponse")>  _
        Function actualizarAdquirienteAClienteAsync(ByVal request As wsAdq.actualizarAdquirienteACliente) As System.Threading.Tasks.Task(Of wsAdq.actualizarAdquirienteAClienteResponse)
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
            "a.com/IServiciosAdquiriente/crearAdquirienteConUsuarioACliente", ReplyAction:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
            "a.com/IServiciosAdquiriente/crearAdquirienteConUsuarioAClienteResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(wsAdq.ExcepcionServiciosTecnica), Action:="http://www.w3.org/2005/08/addressing/soap/fault", Name:="ExcepcionServiciosTecnica"),  _
         System.ServiceModel.FaultContractAttribute(GetType(wsAdq.ExcepcionServiciosNegocio), Action:="http://www.w3.org/2005/08/addressing/soap/fault", Name:="ExcepcionServiciosNegocio"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function crearAdquirienteConUsuarioACliente(ByVal request As wsAdq.crearAdquirienteConUsuarioACliente) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> wsAdq.crearAdquirienteConUsuarioAClienteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
            "a.com/IServiciosAdquiriente/crearAdquirienteConUsuarioACliente", ReplyAction:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
            "a.com/IServiciosAdquiriente/crearAdquirienteConUsuarioAClienteResponse")>  _
        Function crearAdquirienteConUsuarioAClienteAsync(ByVal request As wsAdq.crearAdquirienteConUsuarioACliente) As System.Threading.Tasks.Task(Of wsAdq.crearAdquirienteConUsuarioAClienteResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="actualizarAdquirienteACliente", WrapperNamespace:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
        "a.com/", IsWrapped:=true)>  _
    Partial Public Class actualizarAdquirienteACliente
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
            "a.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public adquiriente As wsAdq.identificacionAdquirienteWS
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
            "a.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public informacionAdquiriente As wsAdq.adquirienteActualizaWS
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
            "a.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute("camposDinamicosAdquiriente", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public camposDinamicosAdquiriente() As wsAdq.camposDinamicosWS
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal adquiriente As wsAdq.identificacionAdquirienteWS, ByVal informacionAdquiriente As wsAdq.adquirienteActualizaWS, ByVal camposDinamicosAdquiriente() As wsAdq.camposDinamicosWS)
            MyBase.New
            Me.adquiriente = adquiriente
            Me.informacionAdquiriente = informacionAdquiriente
            Me.camposDinamicosAdquiriente = camposDinamicosAdquiriente
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="actualizarAdquirienteAClienteResponse", WrapperNamespace:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
        "a.com/", IsWrapped:=true)>  _
    Partial Public Class actualizarAdquirienteAClienteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
            "a.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
        "a.com/")>  _
    Partial Public Class adquirienteWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private acuerdoFisicoFacturacionElectronicaField As Boolean
        
        Private acuerdoFisicoFacturacionElectronicaFieldSpecified As Boolean
        
        Private adjuntarPdfNotificacionesField As Boolean
        
        Private adjuntarPdfNotificacionesFieldSpecified As Boolean
        
        Private adjuntarXmlNotificacionesField As Boolean
        
        Private adjuntarXmlNotificacionesFieldSpecified As Boolean
        
        Private apellidosField As String
        
        Private camposDinamicosAdquirientesField() As camposDinamicosWS
        
        Private cantidadDiasAceptacionAutomaticaField As Integer
        
        Private ciudadExtranjeraField As String
        
        Private codigoCiudadField As String
        
        Private codigoDepartamentoField As String
        
        Private codigoPaisField As String
        
        Private direccionField As String
        
        Private emailPrincipalField As String
        
        Private emailSecundariosField As String
        
        Private enviarCorreoCertificadoField As Boolean
        
        Private enviarCorreoCertificadoFieldSpecified As Boolean
        
        Private enviarCorreoDeBienvenidaField As Boolean
        
        Private enviarCorreoDeBienvenidaFieldSpecified As Boolean
        
        Private enviarFisicoField As Boolean
        
        Private enviarFisicoFieldSpecified As Boolean
        
        Private enviarNotificacionesField As Boolean
        
        Private enviarNotificacionesFieldSpecified As Boolean
        
        Private enviarPlataformaFacturacionField As Boolean
        
        Private enviarPlataformaFacturacionFieldSpecified As Boolean
        
        Private faxField As String
        
        Private formatoFacturaField As String
        
        Private idClienteCreadorField As String
        
        Private identificacionAdquirienteWSField As identificacionAdquirienteWS
        
        Private naturalezaField As enumNaturalezaPersona
        
        Private naturalezaFieldSpecified As Boolean
        
        Private nombreField As String
        
        Private observacionesField As String
        
        Private razonSocialField As String
        
        Private registradoEnCatalogoField As Boolean
        
        Private registradoEnCatalogoFieldSpecified As Boolean
        
        Private telefonoField As String
        
        Private tipoEstablecimientoField As String
        
        Private tipoObligacionField As String
        
        Private tipoUsuarioAduaneroField As String
        
        Private tiposRepresentacionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property acuerdoFisicoFacturacionElectronica() As Boolean
            Get
                Return Me.acuerdoFisicoFacturacionElectronicaField
            End Get
            Set
                Me.acuerdoFisicoFacturacionElectronicaField = value
                Me.RaisePropertyChanged("acuerdoFisicoFacturacionElectronica")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property acuerdoFisicoFacturacionElectronicaSpecified() As Boolean
            Get
                Return Me.acuerdoFisicoFacturacionElectronicaFieldSpecified
            End Get
            Set
                Me.acuerdoFisicoFacturacionElectronicaFieldSpecified = value
                Me.RaisePropertyChanged("acuerdoFisicoFacturacionElectronicaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property adjuntarPdfNotificaciones() As Boolean
            Get
                Return Me.adjuntarPdfNotificacionesField
            End Get
            Set
                Me.adjuntarPdfNotificacionesField = value
                Me.RaisePropertyChanged("adjuntarPdfNotificaciones")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property adjuntarPdfNotificacionesSpecified() As Boolean
            Get
                Return Me.adjuntarPdfNotificacionesFieldSpecified
            End Get
            Set
                Me.adjuntarPdfNotificacionesFieldSpecified = value
                Me.RaisePropertyChanged("adjuntarPdfNotificacionesSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property adjuntarXmlNotificaciones() As Boolean
            Get
                Return Me.adjuntarXmlNotificacionesField
            End Get
            Set
                Me.adjuntarXmlNotificacionesField = value
                Me.RaisePropertyChanged("adjuntarXmlNotificaciones")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property adjuntarXmlNotificacionesSpecified() As Boolean
            Get
                Return Me.adjuntarXmlNotificacionesFieldSpecified
            End Get
            Set
                Me.adjuntarXmlNotificacionesFieldSpecified = value
                Me.RaisePropertyChanged("adjuntarXmlNotificacionesSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property apellidos() As String
            Get
                Return Me.apellidosField
            End Get
            Set
                Me.apellidosField = value
                Me.RaisePropertyChanged("apellidos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("camposDinamicosAdquirientes", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=4)>  _
        Public Property camposDinamicosAdquirientes() As camposDinamicosWS()
            Get
                Return Me.camposDinamicosAdquirientesField
            End Get
            Set
                Me.camposDinamicosAdquirientesField = value
                Me.RaisePropertyChanged("camposDinamicosAdquirientes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property cantidadDiasAceptacionAutomatica() As Integer
            Get
                Return Me.cantidadDiasAceptacionAutomaticaField
            End Get
            Set
                Me.cantidadDiasAceptacionAutomaticaField = value
                Me.RaisePropertyChanged("cantidadDiasAceptacionAutomatica")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property ciudadExtranjera() As String
            Get
                Return Me.ciudadExtranjeraField
            End Get
            Set
                Me.ciudadExtranjeraField = value
                Me.RaisePropertyChanged("ciudadExtranjera")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property codigoCiudad() As String
            Get
                Return Me.codigoCiudadField
            End Get
            Set
                Me.codigoCiudadField = value
                Me.RaisePropertyChanged("codigoCiudad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property codigoDepartamento() As String
            Get
                Return Me.codigoDepartamentoField
            End Get
            Set
                Me.codigoDepartamentoField = value
                Me.RaisePropertyChanged("codigoDepartamento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property codigoPais() As String
            Get
                Return Me.codigoPaisField
            End Get
            Set
                Me.codigoPaisField = value
                Me.RaisePropertyChanged("codigoPais")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
                Me.RaisePropertyChanged("direccion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property emailPrincipal() As String
            Get
                Return Me.emailPrincipalField
            End Get
            Set
                Me.emailPrincipalField = value
                Me.RaisePropertyChanged("emailPrincipal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property emailSecundarios() As String
            Get
                Return Me.emailSecundariosField
            End Get
            Set
                Me.emailSecundariosField = value
                Me.RaisePropertyChanged("emailSecundarios")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property enviarCorreoCertificado() As Boolean
            Get
                Return Me.enviarCorreoCertificadoField
            End Get
            Set
                Me.enviarCorreoCertificadoField = value
                Me.RaisePropertyChanged("enviarCorreoCertificado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property enviarCorreoCertificadoSpecified() As Boolean
            Get
                Return Me.enviarCorreoCertificadoFieldSpecified
            End Get
            Set
                Me.enviarCorreoCertificadoFieldSpecified = value
                Me.RaisePropertyChanged("enviarCorreoCertificadoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=14)>  _
        Public Property enviarCorreoDeBienvenida() As Boolean
            Get
                Return Me.enviarCorreoDeBienvenidaField
            End Get
            Set
                Me.enviarCorreoDeBienvenidaField = value
                Me.RaisePropertyChanged("enviarCorreoDeBienvenida")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property enviarCorreoDeBienvenidaSpecified() As Boolean
            Get
                Return Me.enviarCorreoDeBienvenidaFieldSpecified
            End Get
            Set
                Me.enviarCorreoDeBienvenidaFieldSpecified = value
                Me.RaisePropertyChanged("enviarCorreoDeBienvenidaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=15)>  _
        Public Property enviarFisico() As Boolean
            Get
                Return Me.enviarFisicoField
            End Get
            Set
                Me.enviarFisicoField = value
                Me.RaisePropertyChanged("enviarFisico")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property enviarFisicoSpecified() As Boolean
            Get
                Return Me.enviarFisicoFieldSpecified
            End Get
            Set
                Me.enviarFisicoFieldSpecified = value
                Me.RaisePropertyChanged("enviarFisicoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=16)>  _
        Public Property enviarNotificaciones() As Boolean
            Get
                Return Me.enviarNotificacionesField
            End Get
            Set
                Me.enviarNotificacionesField = value
                Me.RaisePropertyChanged("enviarNotificaciones")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property enviarNotificacionesSpecified() As Boolean
            Get
                Return Me.enviarNotificacionesFieldSpecified
            End Get
            Set
                Me.enviarNotificacionesFieldSpecified = value
                Me.RaisePropertyChanged("enviarNotificacionesSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=17)>  _
        Public Property enviarPlataformaFacturacion() As Boolean
            Get
                Return Me.enviarPlataformaFacturacionField
            End Get
            Set
                Me.enviarPlataformaFacturacionField = value
                Me.RaisePropertyChanged("enviarPlataformaFacturacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property enviarPlataformaFacturacionSpecified() As Boolean
            Get
                Return Me.enviarPlataformaFacturacionFieldSpecified
            End Get
            Set
                Me.enviarPlataformaFacturacionFieldSpecified = value
                Me.RaisePropertyChanged("enviarPlataformaFacturacionSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=18)>  _
        Public Property fax() As String
            Get
                Return Me.faxField
            End Get
            Set
                Me.faxField = value
                Me.RaisePropertyChanged("fax")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=19)>  _
        Public Property formatoFactura() As String
            Get
                Return Me.formatoFacturaField
            End Get
            Set
                Me.formatoFacturaField = value
                Me.RaisePropertyChanged("formatoFactura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=20)>  _
        Public Property idClienteCreador() As String
            Get
                Return Me.idClienteCreadorField
            End Get
            Set
                Me.idClienteCreadorField = value
                Me.RaisePropertyChanged("idClienteCreador")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=21)>  _
        Public Property identificacionAdquirienteWS() As identificacionAdquirienteWS
            Get
                Return Me.identificacionAdquirienteWSField
            End Get
            Set
                Me.identificacionAdquirienteWSField = value
                Me.RaisePropertyChanged("identificacionAdquirienteWS")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=22)>  _
        Public Property naturaleza() As enumNaturalezaPersona
            Get
                Return Me.naturalezaField
            End Get
            Set
                Me.naturalezaField = value
                Me.RaisePropertyChanged("naturaleza")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property naturalezaSpecified() As Boolean
            Get
                Return Me.naturalezaFieldSpecified
            End Get
            Set
                Me.naturalezaFieldSpecified = value
                Me.RaisePropertyChanged("naturalezaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=23)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=24)>  _
        Public Property observaciones() As String
            Get
                Return Me.observacionesField
            End Get
            Set
                Me.observacionesField = value
                Me.RaisePropertyChanged("observaciones")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=25)>  _
        Public Property razonSocial() As String
            Get
                Return Me.razonSocialField
            End Get
            Set
                Me.razonSocialField = value
                Me.RaisePropertyChanged("razonSocial")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=26)>  _
        Public Property registradoEnCatalogo() As Boolean
            Get
                Return Me.registradoEnCatalogoField
            End Get
            Set
                Me.registradoEnCatalogoField = value
                Me.RaisePropertyChanged("registradoEnCatalogo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property registradoEnCatalogoSpecified() As Boolean
            Get
                Return Me.registradoEnCatalogoFieldSpecified
            End Get
            Set
                Me.registradoEnCatalogoFieldSpecified = value
                Me.RaisePropertyChanged("registradoEnCatalogoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=27)>  _
        Public Property telefono() As String
            Get
                Return Me.telefonoField
            End Get
            Set
                Me.telefonoField = value
                Me.RaisePropertyChanged("telefono")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=28)>  _
        Public Property tipoEstablecimiento() As String
            Get
                Return Me.tipoEstablecimientoField
            End Get
            Set
                Me.tipoEstablecimientoField = value
                Me.RaisePropertyChanged("tipoEstablecimiento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=29)>  _
        Public Property tipoObligacion() As String
            Get
                Return Me.tipoObligacionField
            End Get
            Set
                Me.tipoObligacionField = value
                Me.RaisePropertyChanged("tipoObligacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=30)>  _
        Public Property tipoUsuarioAduanero() As String
            Get
                Return Me.tipoUsuarioAduaneroField
            End Get
            Set
                Me.tipoUsuarioAduaneroField = value
                Me.RaisePropertyChanged("tipoUsuarioAduanero")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=31)>  _
        Public Property tiposRepresentacion() As String
            Get
                Return Me.tiposRepresentacionField
            End Get
            Set
                Me.tiposRepresentacionField = value
                Me.RaisePropertyChanged("tiposRepresentacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
        "a.com/")>  _
    Public Enum enumNaturalezaPersona
        
        '''<remarks/>
        JURIDICA
        
        '''<remarks/>
        NATURAL
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
        "a.com/")>  _
    Partial Public Class usuarioAdquirienteWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private contrasenaField As String
        
        Private generarContrasenaField As Boolean
        
        Private generarContrasenaFieldSpecified As Boolean
        
        Private nombreUsuarioField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property contrasena() As String
            Get
                Return Me.contrasenaField
            End Get
            Set
                Me.contrasenaField = value
                Me.RaisePropertyChanged("contrasena")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property generarContrasena() As Boolean
            Get
                Return Me.generarContrasenaField
            End Get
            Set
                Me.generarContrasenaField = value
                Me.RaisePropertyChanged("generarContrasena")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property generarContrasenaSpecified() As Boolean
            Get
                Return Me.generarContrasenaFieldSpecified
            End Get
            Set
                Me.generarContrasenaFieldSpecified = value
                Me.RaisePropertyChanged("generarContrasenaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property nombreUsuario() As String
            Get
                Return Me.nombreUsuarioField
            End Get
            Set
                Me.nombreUsuarioField = value
                Me.RaisePropertyChanged("nombreUsuario")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="crearAdquirienteConUsuarioACliente", WrapperNamespace:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
        "a.com/", IsWrapped:=true)>  _
    Partial Public Class crearAdquirienteConUsuarioACliente
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
            "a.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public adquiriente As wsAdq.adquirienteWS
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
            "a.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public usuario As wsAdq.usuarioAdquirienteWS
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal adquiriente As wsAdq.adquirienteWS, ByVal usuario As wsAdq.usuarioAdquirienteWS)
            MyBase.New
            Me.adquiriente = adquiriente
            Me.usuario = usuario
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="crearAdquirienteConUsuarioAClienteResponse", WrapperNamespace:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
        "a.com/", IsWrapped:=true)>  _
    Partial Public Class crearAdquirienteConUsuarioAClienteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.adquiriente.cliente.webservices.servicios.certifactura.certicamar"& _ 
            "a.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServiciosAdquirienteChannel
        Inherits wsAdq.IServiciosAdquiriente, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiciosAdquirienteClient
        Inherits System.ServiceModel.ClientBase(Of wsAdq.IServiciosAdquiriente)
        Implements wsAdq.IServiciosAdquiriente
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAdq_IServiciosAdquiriente_actualizarAdquirienteACliente(ByVal request As wsAdq.actualizarAdquirienteACliente) As wsAdq.actualizarAdquirienteAClienteResponse Implements wsAdq.IServiciosAdquiriente.actualizarAdquirienteACliente
            Return MyBase.Channel.actualizarAdquirienteACliente(request)
        End Function
        
        Public Function actualizarAdquirienteACliente(ByVal adquiriente As wsAdq.identificacionAdquirienteWS, ByVal informacionAdquiriente As wsAdq.adquirienteActualizaWS, ByVal camposDinamicosAdquiriente() As wsAdq.camposDinamicosWS) As String
            Dim inValue As wsAdq.actualizarAdquirienteACliente = New wsAdq.actualizarAdquirienteACliente()
            inValue.adquiriente = adquiriente
            inValue.informacionAdquiriente = informacionAdquiriente
            inValue.camposDinamicosAdquiriente = camposDinamicosAdquiriente
            Dim retVal As wsAdq.actualizarAdquirienteAClienteResponse = CType(Me,wsAdq.IServiciosAdquiriente).actualizarAdquirienteACliente(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAdq_IServiciosAdquiriente_actualizarAdquirienteAClienteAsync(ByVal request As wsAdq.actualizarAdquirienteACliente) As System.Threading.Tasks.Task(Of wsAdq.actualizarAdquirienteAClienteResponse) Implements wsAdq.IServiciosAdquiriente.actualizarAdquirienteAClienteAsync
            Return MyBase.Channel.actualizarAdquirienteAClienteAsync(request)
        End Function
        
        Public Function actualizarAdquirienteAClienteAsync(ByVal adquiriente As wsAdq.identificacionAdquirienteWS, ByVal informacionAdquiriente As wsAdq.adquirienteActualizaWS, ByVal camposDinamicosAdquiriente() As wsAdq.camposDinamicosWS) As System.Threading.Tasks.Task(Of wsAdq.actualizarAdquirienteAClienteResponse)
            Dim inValue As wsAdq.actualizarAdquirienteACliente = New wsAdq.actualizarAdquirienteACliente()
            inValue.adquiriente = adquiriente
            inValue.informacionAdquiriente = informacionAdquiriente
            inValue.camposDinamicosAdquiriente = camposDinamicosAdquiriente
            Return CType(Me,wsAdq.IServiciosAdquiriente).actualizarAdquirienteAClienteAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAdq_IServiciosAdquiriente_crearAdquirienteConUsuarioACliente(ByVal request As wsAdq.crearAdquirienteConUsuarioACliente) As wsAdq.crearAdquirienteConUsuarioAClienteResponse Implements wsAdq.IServiciosAdquiriente.crearAdquirienteConUsuarioACliente
            Return MyBase.Channel.crearAdquirienteConUsuarioACliente(request)
        End Function
        
        Public Function crearAdquirienteConUsuarioACliente(ByVal adquiriente As wsAdq.adquirienteWS, ByVal usuario As wsAdq.usuarioAdquirienteWS) As String
            Dim inValue As wsAdq.crearAdquirienteConUsuarioACliente = New wsAdq.crearAdquirienteConUsuarioACliente()
            inValue.adquiriente = adquiriente
            inValue.usuario = usuario
            Dim retVal As wsAdq.crearAdquirienteConUsuarioAClienteResponse = CType(Me,wsAdq.IServiciosAdquiriente).crearAdquirienteConUsuarioACliente(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAdq_IServiciosAdquiriente_crearAdquirienteConUsuarioAClienteAsync(ByVal request As wsAdq.crearAdquirienteConUsuarioACliente) As System.Threading.Tasks.Task(Of wsAdq.crearAdquirienteConUsuarioAClienteResponse) Implements wsAdq.IServiciosAdquiriente.crearAdquirienteConUsuarioAClienteAsync
            Return MyBase.Channel.crearAdquirienteConUsuarioAClienteAsync(request)
        End Function
        
        Public Function crearAdquirienteConUsuarioAClienteAsync(ByVal adquiriente As wsAdq.adquirienteWS, ByVal usuario As wsAdq.usuarioAdquirienteWS) As System.Threading.Tasks.Task(Of wsAdq.crearAdquirienteConUsuarioAClienteResponse)
            Dim inValue As wsAdq.crearAdquirienteConUsuarioACliente = New wsAdq.crearAdquirienteConUsuarioACliente()
            inValue.adquiriente = adquiriente
            inValue.usuario = usuario
            Return CType(Me,wsAdq.IServiciosAdquiriente).crearAdquirienteConUsuarioAClienteAsync(inValue)
        End Function
    End Class
End Namespace
