'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace wsNota
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class ExcepcionServiciosTecnica
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private campoField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property campo() As String
            Get
                Return Me.campoField
            End Get
            Set
                Me.campoField = value
                Me.RaisePropertyChanged("campo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("mensaje")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class atributoAdicional
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nombreAtributoField As String
        
        Private valorField As String
        
        Private tipoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property nombreAtributo() As String
            Get
                Return Me.nombreAtributoField
            End Get
            Set
                Me.nombreAtributoField = value
                Me.RaisePropertyChanged("nombreAtributo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property valor() As String
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("valor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
                Me.RaisePropertyChanged("tipo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class documentoPersonalizado
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private atributosAdicionalesField() As atributoAdicional
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("AtributoAdicional", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property AtributosAdicionales() As atributoAdicional()
            Get
                Return Me.atributosAdicionalesField
            End Get
            Set
                Me.atributosAdicionalesField = value
                Me.RaisePropertyChanged("AtributosAdicionales")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class impuestoDeduccionWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private baseGravableField As Decimal
        
        Private baseGravableFieldSpecified As Boolean
        
        Private nombreField As String
        
        Private valorField As Decimal
        
        Private valorFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property baseGravable() As Decimal
            Get
                Return Me.baseGravableField
            End Get
            Set
                Me.baseGravableField = value
                Me.RaisePropertyChanged("baseGravable")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property baseGravableSpecified() As Boolean
            Get
                Return Me.baseGravableFieldSpecified
            End Get
            Set
                Me.baseGravableFieldSpecified = value
                Me.RaisePropertyChanged("baseGravableSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("valor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property valorSpecified() As Boolean
            Get
                Return Me.valorFieldSpecified
            End Get
            Set
                Me.valorFieldSpecified = value
                Me.RaisePropertyChanged("valorSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class impuestoIVA
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nombreField As String
        
        Private porcentualField As Decimal
        
        Private porcentualFieldSpecified As Boolean
        
        Private valorField As Decimal
        
        Private valorFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property porcentual() As Decimal
            Get
                Return Me.porcentualField
            End Get
            Set
                Me.porcentualField = value
                Me.RaisePropertyChanged("porcentual")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property porcentualSpecified() As Boolean
            Get
                Return Me.porcentualFieldSpecified
            End Get
            Set
                Me.porcentualFieldSpecified = value
                Me.RaisePropertyChanged("porcentualSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("valor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property valorSpecified() As Boolean
            Get
                Return Me.valorFieldSpecified
            End Get
            Set
                Me.valorFieldSpecified = value
                Me.RaisePropertyChanged("valorSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class impuestoICA
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nombreField As String
        
        Private valorField As Decimal
        
        Private valorFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("valor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property valorSpecified() As Boolean
            Get
                Return Me.valorFieldSpecified
            End Get
            Set
                Me.valorFieldSpecified = value
                Me.RaisePropertyChanged("valorSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class impuestoAlConsumo
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nombreField As String
        
        Private porcentualField As Decimal
        
        Private porcentualFieldSpecified As Boolean
        
        Private valorField As Decimal
        
        Private valorFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property porcentual() As Decimal
            Get
                Return Me.porcentualField
            End Get
            Set
                Me.porcentualField = value
                Me.RaisePropertyChanged("porcentual")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property porcentualSpecified() As Boolean
            Get
                Return Me.porcentualFieldSpecified
            End Get
            Set
                Me.porcentualFieldSpecified = value
                Me.RaisePropertyChanged("porcentualSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("valor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property valorSpecified() As Boolean
            Get
                Return Me.valorFieldSpecified
            End Get
            Set
                Me.valorFieldSpecified = value
                Me.RaisePropertyChanged("valorSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class atributoAdicionalProdWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nombreAtributoField As String
        
        Private valorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property nombreAtributo() As String
            Get
                Return Me.nombreAtributoField
            End Get
            Set
                Me.nombreAtributoField = value
                Me.RaisePropertyChanged("nombreAtributo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property valor() As String
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("valor")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class productoCertifacturaWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private atributosAdicionalesProdField() As atributoAdicionalProdWS
        
        Private cantidadField As Decimal
        
        Private cantidadFieldSpecified As Boolean
        
        Private descripcionField As String
        
        Private identificadorField As String
        
        Private imprimibleField As Boolean
        
        Private imprimibleFieldSpecified As Boolean
        
        Private impuestoAlConsumoField As impuestoAlConsumo
        
        Private impuestoICAField As impuestoICA
        
        Private impuestoIVAField As impuestoIVA
        
        Private listaImpuestosDeduccionesField() As impuestoDeduccionWS
        
        Private pagableField As Boolean
        
        Private pagableFieldSpecified As Boolean
        
        Private valorUnitarioField As Decimal
        
        Private valorUnitarioFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("atributoAdicionalProd", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property atributosAdicionalesProd() As atributoAdicionalProdWS()
            Get
                Return Me.atributosAdicionalesProdField
            End Get
            Set
                Me.atributosAdicionalesProdField = value
                Me.RaisePropertyChanged("atributosAdicionalesProd")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
                Me.RaisePropertyChanged("cantidad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property cantidadSpecified() As Boolean
            Get
                Return Me.cantidadFieldSpecified
            End Get
            Set
                Me.cantidadFieldSpecified = value
                Me.RaisePropertyChanged("cantidadSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("descripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property identificador() As String
            Get
                Return Me.identificadorField
            End Get
            Set
                Me.identificadorField = value
                Me.RaisePropertyChanged("identificador")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property imprimible() As Boolean
            Get
                Return Me.imprimibleField
            End Get
            Set
                Me.imprimibleField = value
                Me.RaisePropertyChanged("imprimible")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property imprimibleSpecified() As Boolean
            Get
                Return Me.imprimibleFieldSpecified
            End Get
            Set
                Me.imprimibleFieldSpecified = value
                Me.RaisePropertyChanged("imprimibleSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property impuestoAlConsumo() As impuestoAlConsumo
            Get
                Return Me.impuestoAlConsumoField
            End Get
            Set
                Me.impuestoAlConsumoField = value
                Me.RaisePropertyChanged("impuestoAlConsumo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property impuestoICA() As impuestoICA
            Get
                Return Me.impuestoICAField
            End Get
            Set
                Me.impuestoICAField = value
                Me.RaisePropertyChanged("impuestoICA")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property impuestoIVA() As impuestoIVA
            Get
                Return Me.impuestoIVAField
            End Get
            Set
                Me.impuestoIVAField = value
                Me.RaisePropertyChanged("impuestoIVA")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("listaImpuestosDeducciones", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=8)>  _
        Public Property listaImpuestosDeducciones() As impuestoDeduccionWS()
            Get
                Return Me.listaImpuestosDeduccionesField
            End Get
            Set
                Me.listaImpuestosDeduccionesField = value
                Me.RaisePropertyChanged("listaImpuestosDeducciones")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property pagable() As Boolean
            Get
                Return Me.pagableField
            End Get
            Set
                Me.pagableField = value
                Me.RaisePropertyChanged("pagable")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property pagableSpecified() As Boolean
            Get
                Return Me.pagableFieldSpecified
            End Get
            Set
                Me.pagableFieldSpecified = value
                Me.RaisePropertyChanged("pagableSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property valorUnitario() As Decimal
            Get
                Return Me.valorUnitarioField
            End Get
            Set
                Me.valorUnitarioField = value
                Me.RaisePropertyChanged("valorUnitario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property valorUnitarioSpecified() As Boolean
            Get
                Return Me.valorUnitarioFieldSpecified
            End Get
            Set
                Me.valorUnitarioFieldSpecified = value
                Me.RaisePropertyChanged("valorUnitarioSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class identificacionClienteWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoDocumentoDianField As Integer
        
        Private codigoDocumentoDianFieldSpecified As Boolean
        
        Private numeroIdentificacionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codigoDocumentoDian() As Integer
            Get
                Return Me.codigoDocumentoDianField
            End Get
            Set
                Me.codigoDocumentoDianField = value
                Me.RaisePropertyChanged("codigoDocumentoDian")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property codigoDocumentoDianSpecified() As Boolean
            Get
                Return Me.codigoDocumentoDianFieldSpecified
            End Get
            Set
                Me.codigoDocumentoDianFieldSpecified = value
                Me.RaisePropertyChanged("codigoDocumentoDianSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property numeroIdentificacion() As String
            Get
                Return Me.numeroIdentificacionField
            End Get
            Set
                Me.numeroIdentificacionField = value
                Me.RaisePropertyChanged("numeroIdentificacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(notaCreditoElectronicaWS)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public MustInherit Class documentoElectronicoWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private identificacionReceptorField As identificacionClienteWS
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property identificacionReceptor() As identificacionClienteWS
            Get
                Return Me.identificacionReceptorField
            End Get
            Set
                Me.identificacionReceptorField = value
                Me.RaisePropertyChanged("identificacionReceptor")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class notaCreditoElectronicaWS
        Inherits documentoElectronicoWS
        
        Private codigoMonedaField As String
        
        Private conceptoNotaField As String
        
        Private fechaExpedicionField As String
        
        Private fechaVencimientoField As String
        
        Private identificadorFacturaField As String
        
        Private identificadoresFacturasField() As String
        
        Private nombreSucursalField As String
        
        Private numeroNotaField As Long
        
        Private numeroNotaFieldSpecified As Boolean
        
        Private observacionesField As String
        
        Private perfilEmisionField As enumPerfilPersona
        
        Private perfilEmisionFieldSpecified As Boolean
        
        Private perfilUsuarioField As enumPerfilPersona
        
        Private perfilUsuarioFieldSpecified As Boolean
        
        Private prefijoNotaField As String
        
        Private productosField() As productoCertifacturaWS
        
        Private subtotalNotaCreditoElectronicaField As Decimal
        
        Private subtotalNotaCreditoElectronicaFieldSpecified As Boolean
        
        Private subtotalesImpuestosDeduccionField() As impuestoDeduccionWS
        
        Private tipoFacturaField As String
        
        Private totalAnticiposField As Decimal
        
        Private totalAnticiposFieldSpecified As Boolean
        
        Private totalDescuentosField As Decimal
        
        Private totalDescuentosFieldSpecified As Boolean
        
        Private totalNotaCreditoElectronicaField As Decimal
        
        Private totalNotaCreditoElectronicaFieldSpecified As Boolean
        
        Private totalOtrosCostosField As Decimal
        
        Private totalOtrosCostosFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codigoMoneda() As String
            Get
                Return Me.codigoMonedaField
            End Get
            Set
                Me.codigoMonedaField = value
                Me.RaisePropertyChanged("codigoMoneda")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property conceptoNota() As String
            Get
                Return Me.conceptoNotaField
            End Get
            Set
                Me.conceptoNotaField = value
                Me.RaisePropertyChanged("conceptoNota")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property fechaExpedicion() As String
            Get
                Return Me.fechaExpedicionField
            End Get
            Set
                Me.fechaExpedicionField = value
                Me.RaisePropertyChanged("fechaExpedicion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property fechaVencimiento() As String
            Get
                Return Me.fechaVencimientoField
            End Get
            Set
                Me.fechaVencimientoField = value
                Me.RaisePropertyChanged("fechaVencimiento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property identificadorFactura() As String
            Get
                Return Me.identificadorFacturaField
            End Get
            Set
                Me.identificadorFacturaField = value
                Me.RaisePropertyChanged("identificadorFactura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5),  _
         System.Xml.Serialization.XmlArrayItemAttribute("identificadorFactura", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property identificadoresFacturas() As String()
            Get
                Return Me.identificadoresFacturasField
            End Get
            Set
                Me.identificadoresFacturasField = value
                Me.RaisePropertyChanged("identificadoresFacturas")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property nombreSucursal() As String
            Get
                Return Me.nombreSucursalField
            End Get
            Set
                Me.nombreSucursalField = value
                Me.RaisePropertyChanged("nombreSucursal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property numeroNota() As Long
            Get
                Return Me.numeroNotaField
            End Get
            Set
                Me.numeroNotaField = value
                Me.RaisePropertyChanged("numeroNota")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property numeroNotaSpecified() As Boolean
            Get
                Return Me.numeroNotaFieldSpecified
            End Get
            Set
                Me.numeroNotaFieldSpecified = value
                Me.RaisePropertyChanged("numeroNotaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property observaciones() As String
            Get
                Return Me.observacionesField
            End Get
            Set
                Me.observacionesField = value
                Me.RaisePropertyChanged("observaciones")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property perfilEmision() As enumPerfilPersona
            Get
                Return Me.perfilEmisionField
            End Get
            Set
                Me.perfilEmisionField = value
                Me.RaisePropertyChanged("perfilEmision")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property perfilEmisionSpecified() As Boolean
            Get
                Return Me.perfilEmisionFieldSpecified
            End Get
            Set
                Me.perfilEmisionFieldSpecified = value
                Me.RaisePropertyChanged("perfilEmisionSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property perfilUsuario() As enumPerfilPersona
            Get
                Return Me.perfilUsuarioField
            End Get
            Set
                Me.perfilUsuarioField = value
                Me.RaisePropertyChanged("perfilUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property perfilUsuarioSpecified() As Boolean
            Get
                Return Me.perfilUsuarioFieldSpecified
            End Get
            Set
                Me.perfilUsuarioFieldSpecified = value
                Me.RaisePropertyChanged("perfilUsuarioSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property prefijoNota() As String
            Get
                Return Me.prefijoNotaField
            End Get
            Set
                Me.prefijoNotaField = value
                Me.RaisePropertyChanged("prefijoNota")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("productos", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=12)>  _
        Public Property productos() As productoCertifacturaWS()
            Get
                Return Me.productosField
            End Get
            Set
                Me.productosField = value
                Me.RaisePropertyChanged("productos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property subtotalNotaCreditoElectronica() As Decimal
            Get
                Return Me.subtotalNotaCreditoElectronicaField
            End Get
            Set
                Me.subtotalNotaCreditoElectronicaField = value
                Me.RaisePropertyChanged("subtotalNotaCreditoElectronica")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property subtotalNotaCreditoElectronicaSpecified() As Boolean
            Get
                Return Me.subtotalNotaCreditoElectronicaFieldSpecified
            End Get
            Set
                Me.subtotalNotaCreditoElectronicaFieldSpecified = value
                Me.RaisePropertyChanged("subtotalNotaCreditoElectronicaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("subtotalesImpuestosDeduccion", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=14)>  _
        Public Property subtotalesImpuestosDeduccion() As impuestoDeduccionWS()
            Get
                Return Me.subtotalesImpuestosDeduccionField
            End Get
            Set
                Me.subtotalesImpuestosDeduccionField = value
                Me.RaisePropertyChanged("subtotalesImpuestosDeduccion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=15)>  _
        Public Property tipoFactura() As String
            Get
                Return Me.tipoFacturaField
            End Get
            Set
                Me.tipoFacturaField = value
                Me.RaisePropertyChanged("tipoFactura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=16)>  _
        Public Property totalAnticipos() As Decimal
            Get
                Return Me.totalAnticiposField
            End Get
            Set
                Me.totalAnticiposField = value
                Me.RaisePropertyChanged("totalAnticipos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property totalAnticiposSpecified() As Boolean
            Get
                Return Me.totalAnticiposFieldSpecified
            End Get
            Set
                Me.totalAnticiposFieldSpecified = value
                Me.RaisePropertyChanged("totalAnticiposSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=17)>  _
        Public Property totalDescuentos() As Decimal
            Get
                Return Me.totalDescuentosField
            End Get
            Set
                Me.totalDescuentosField = value
                Me.RaisePropertyChanged("totalDescuentos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property totalDescuentosSpecified() As Boolean
            Get
                Return Me.totalDescuentosFieldSpecified
            End Get
            Set
                Me.totalDescuentosFieldSpecified = value
                Me.RaisePropertyChanged("totalDescuentosSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=18)>  _
        Public Property totalNotaCreditoElectronica() As Decimal
            Get
                Return Me.totalNotaCreditoElectronicaField
            End Get
            Set
                Me.totalNotaCreditoElectronicaField = value
                Me.RaisePropertyChanged("totalNotaCreditoElectronica")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property totalNotaCreditoElectronicaSpecified() As Boolean
            Get
                Return Me.totalNotaCreditoElectronicaFieldSpecified
            End Get
            Set
                Me.totalNotaCreditoElectronicaFieldSpecified = value
                Me.RaisePropertyChanged("totalNotaCreditoElectronicaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=19)>  _
        Public Property totalOtrosCostos() As Decimal
            Get
                Return Me.totalOtrosCostosField
            End Get
            Set
                Me.totalOtrosCostosField = value
                Me.RaisePropertyChanged("totalOtrosCostos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property totalOtrosCostosSpecified() As Boolean
            Get
                Return Me.totalOtrosCostosFieldSpecified
            End Get
            Set
                Me.totalOtrosCostosFieldSpecified = value
                Me.RaisePropertyChanged("totalOtrosCostosSpecified")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/")>  _
    Public Enum enumPerfilPersona
        
        '''<remarks/>
        CLIENTE
        
        '''<remarks/>
        ADQUIRIENTE
        
        '''<remarks/>
        PROVEEDOR
        
        '''<remarks/>
        PLATAFORMA
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class ExcepcionServiciosNegocio
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private campoField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property campo() As String
            Get
                Return Me.campoField
            End Get
            Set
                Me.campoField = value
                Me.RaisePropertyChanged("campo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("mensaje")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class ExcepcionServicios
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private campoField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property campo() As String
            Get
                Return Me.campoField
            End Get
            Set
                Me.campoField = value
                Me.RaisePropertyChanged("campo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("mensaje")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/", ConfigurationName:="wsNota.IServiciosEmitirNotaCreditoElectronica")>  _
    Public Interface IServiciosEmitirNotaCreditoElectronica
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(wsNota.ExcepcionServiciosTecnica), Action:="", Name:="ExcepcionServiciosTecnica"),  _
         System.ServiceModel.FaultContractAttribute(GetType(wsNota.ExcepcionServiciosNegocio), Action:="", Name:="ExcepcionServiciosNegocio"),  _
         System.ServiceModel.FaultContractAttribute(GetType(wsNota.ExcepcionServicios), Action:="", Name:="ExcepcionServicios"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(documentoElectronicoWS))>  _
        Function crearNotaCreditoElectronica(ByVal request As wsNota.crearNotaCreditoElectronica) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> wsNota.crearNotaCreditoElectronicaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function crearNotaCreditoElectronicaAsync(ByVal request As wsNota.crearNotaCreditoElectronica) As System.Threading.Tasks.Task(Of wsNota.crearNotaCreditoElectronicaResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="crearNotaCreditoElectronica", WrapperNamespace:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/", IsWrapped:=true)>  _
    Partial Public Class crearNotaCreditoElectronica
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public notaCreditoElectronicaCanonica As wsNota.notaCreditoElectronicaWS
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public notaEspecializada As wsNota.documentoPersonalizado
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal notaCreditoElectronicaCanonica As wsNota.notaCreditoElectronicaWS, ByVal notaEspecializada As wsNota.documentoPersonalizado)
            MyBase.New
            Me.notaCreditoElectronicaCanonica = notaCreditoElectronicaCanonica
            Me.notaEspecializada = notaEspecializada
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="crearNotaCreditoElectronicaResponse", WrapperNamespace:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/", IsWrapped:=true)>  _
    Partial Public Class crearNotaCreditoElectronicaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.nota.webservices.servicios.certifactura.certicamara.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServiciosEmitirNotaCreditoElectronicaChannel
        Inherits wsNota.IServiciosEmitirNotaCreditoElectronica, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiciosEmitirNotaCreditoElectronicaClient
        Inherits System.ServiceModel.ClientBase(Of wsNota.IServiciosEmitirNotaCreditoElectronica)
        Implements wsNota.IServiciosEmitirNotaCreditoElectronica
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsNota_IServiciosEmitirNotaCreditoElectronica_crearNotaCreditoElectronica(ByVal request As wsNota.crearNotaCreditoElectronica) As wsNota.crearNotaCreditoElectronicaResponse Implements wsNota.IServiciosEmitirNotaCreditoElectronica.crearNotaCreditoElectronica
            Return MyBase.Channel.crearNotaCreditoElectronica(request)
        End Function
        
        Public Function crearNotaCreditoElectronica(ByVal notaCreditoElectronicaCanonica As wsNota.notaCreditoElectronicaWS, ByVal notaEspecializada As wsNota.documentoPersonalizado) As String
            Dim inValue As wsNota.crearNotaCreditoElectronica = New wsNota.crearNotaCreditoElectronica()
            inValue.notaCreditoElectronicaCanonica = notaCreditoElectronicaCanonica
            inValue.notaEspecializada = notaEspecializada
            Dim retVal As wsNota.crearNotaCreditoElectronicaResponse = CType(Me,wsNota.IServiciosEmitirNotaCreditoElectronica).crearNotaCreditoElectronica(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsNota_IServiciosEmitirNotaCreditoElectronica_crearNotaCreditoElectronicaAsync(ByVal request As wsNota.crearNotaCreditoElectronica) As System.Threading.Tasks.Task(Of wsNota.crearNotaCreditoElectronicaResponse) Implements wsNota.IServiciosEmitirNotaCreditoElectronica.crearNotaCreditoElectronicaAsync
            Return MyBase.Channel.crearNotaCreditoElectronicaAsync(request)
        End Function
        
        Public Function crearNotaCreditoElectronicaAsync(ByVal notaCreditoElectronicaCanonica As wsNota.notaCreditoElectronicaWS, ByVal notaEspecializada As wsNota.documentoPersonalizado) As System.Threading.Tasks.Task(Of wsNota.crearNotaCreditoElectronicaResponse)
            Dim inValue As wsNota.crearNotaCreditoElectronica = New wsNota.crearNotaCreditoElectronica()
            inValue.notaCreditoElectronicaCanonica = notaCreditoElectronicaCanonica
            inValue.notaEspecializada = notaEspecializada
            Return CType(Me,wsNota.IServiciosEmitirNotaCreditoElectronica).crearNotaCreditoElectronicaAsync(inValue)
        End Function
    End Class
End Namespace
