'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace wsFact
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class ExcepcionServiciosTecnica
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private campoField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property campo() As String
            Get
                Return Me.campoField
            End Get
            Set
                Me.campoField = value
                Me.RaisePropertyChanged("campo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("mensaje")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class atributoAdicional
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nombreAtributoField As String
        
        Private valorField As String
        
        Private tipoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property nombreAtributo() As String
            Get
                Return Me.nombreAtributoField
            End Get
            Set
                Me.nombreAtributoField = value
                Me.RaisePropertyChanged("nombreAtributo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property valor() As String
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("valor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
                Me.RaisePropertyChanged("tipo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class documentoPersonalizado
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private atributosAdicionalesField() As atributoAdicional
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("AtributoAdicional", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property AtributosAdicionales() As atributoAdicional()
            Get
                Return Me.atributosAdicionalesField
            End Get
            Set
                Me.atributosAdicionalesField = value
                Me.RaisePropertyChanged("AtributosAdicionales")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class impuestoDeduccionWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private baseGravableField As Decimal
        
        Private baseGravableFieldSpecified As Boolean
        
        Private nombreField As String
        
        Private valorField As Decimal
        
        Private valorFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property baseGravable() As Decimal
            Get
                Return Me.baseGravableField
            End Get
            Set
                Me.baseGravableField = value
                Me.RaisePropertyChanged("baseGravable")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property baseGravableSpecified() As Boolean
            Get
                Return Me.baseGravableFieldSpecified
            End Get
            Set
                Me.baseGravableFieldSpecified = value
                Me.RaisePropertyChanged("baseGravableSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("valor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property valorSpecified() As Boolean
            Get
                Return Me.valorFieldSpecified
            End Get
            Set
                Me.valorFieldSpecified = value
                Me.RaisePropertyChanged("valorSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class impuestoIVA
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nombreField As String
        
        Private porcentualField As Decimal
        
        Private porcentualFieldSpecified As Boolean
        
        Private valorField As Decimal
        
        Private valorFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property porcentual() As Decimal
            Get
                Return Me.porcentualField
            End Get
            Set
                Me.porcentualField = value
                Me.RaisePropertyChanged("porcentual")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property porcentualSpecified() As Boolean
            Get
                Return Me.porcentualFieldSpecified
            End Get
            Set
                Me.porcentualFieldSpecified = value
                Me.RaisePropertyChanged("porcentualSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("valor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property valorSpecified() As Boolean
            Get
                Return Me.valorFieldSpecified
            End Get
            Set
                Me.valorFieldSpecified = value
                Me.RaisePropertyChanged("valorSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class impuestoICA
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nombreField As String
        
        Private valorField As Decimal
        
        Private valorFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("valor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property valorSpecified() As Boolean
            Get
                Return Me.valorFieldSpecified
            End Get
            Set
                Me.valorFieldSpecified = value
                Me.RaisePropertyChanged("valorSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class impuestoAlConsumo
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nombreField As String
        
        Private porcentualField As Decimal
        
        Private porcentualFieldSpecified As Boolean
        
        Private valorField As Decimal
        
        Private valorFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property porcentual() As Decimal
            Get
                Return Me.porcentualField
            End Get
            Set
                Me.porcentualField = value
                Me.RaisePropertyChanged("porcentual")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property porcentualSpecified() As Boolean
            Get
                Return Me.porcentualFieldSpecified
            End Get
            Set
                Me.porcentualFieldSpecified = value
                Me.RaisePropertyChanged("porcentualSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property valor() As Decimal
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("valor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property valorSpecified() As Boolean
            Get
                Return Me.valorFieldSpecified
            End Get
            Set
                Me.valorFieldSpecified = value
                Me.RaisePropertyChanged("valorSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class atributoAdicionalProdWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nombreAtributoField As String
        
        Private valorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property nombreAtributo() As String
            Get
                Return Me.nombreAtributoField
            End Get
            Set
                Me.nombreAtributoField = value
                Me.RaisePropertyChanged("nombreAtributo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property valor() As String
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("valor")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class productoCertifacturaWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private atributosAdicionalesProdField() As atributoAdicionalProdWS
        
        Private cantidadField As Decimal
        
        Private cantidadFieldSpecified As Boolean
        
        Private descripcionField As String
        
        Private identificadorField As String
        
        Private imprimibleField As Boolean
        
        Private imprimibleFieldSpecified As Boolean
        
        Private impuestoAlConsumoField As impuestoAlConsumo
        
        Private impuestoICAField As impuestoICA
        
        Private impuestoIVAField As impuestoIVA
        
        Private listaImpuestosDeduccionesField() As impuestoDeduccionWS
        
        Private pagableField As Boolean
        
        Private pagableFieldSpecified As Boolean
        
        Private valorUnitarioField As Decimal
        
        Private valorUnitarioFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("atributoAdicionalProd", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property atributosAdicionalesProd() As atributoAdicionalProdWS()
            Get
                Return Me.atributosAdicionalesProdField
            End Get
            Set
                Me.atributosAdicionalesProdField = value
                Me.RaisePropertyChanged("atributosAdicionalesProd")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
                Me.RaisePropertyChanged("cantidad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property cantidadSpecified() As Boolean
            Get
                Return Me.cantidadFieldSpecified
            End Get
            Set
                Me.cantidadFieldSpecified = value
                Me.RaisePropertyChanged("cantidadSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("descripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property identificador() As String
            Get
                Return Me.identificadorField
            End Get
            Set
                Me.identificadorField = value
                Me.RaisePropertyChanged("identificador")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property imprimible() As Boolean
            Get
                Return Me.imprimibleField
            End Get
            Set
                Me.imprimibleField = value
                Me.RaisePropertyChanged("imprimible")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property imprimibleSpecified() As Boolean
            Get
                Return Me.imprimibleFieldSpecified
            End Get
            Set
                Me.imprimibleFieldSpecified = value
                Me.RaisePropertyChanged("imprimibleSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property impuestoAlConsumo() As impuestoAlConsumo
            Get
                Return Me.impuestoAlConsumoField
            End Get
            Set
                Me.impuestoAlConsumoField = value
                Me.RaisePropertyChanged("impuestoAlConsumo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property impuestoICA() As impuestoICA
            Get
                Return Me.impuestoICAField
            End Get
            Set
                Me.impuestoICAField = value
                Me.RaisePropertyChanged("impuestoICA")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property impuestoIVA() As impuestoIVA
            Get
                Return Me.impuestoIVAField
            End Get
            Set
                Me.impuestoIVAField = value
                Me.RaisePropertyChanged("impuestoIVA")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("listaImpuestosDeducciones", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=8)>  _
        Public Property listaImpuestosDeducciones() As impuestoDeduccionWS()
            Get
                Return Me.listaImpuestosDeduccionesField
            End Get
            Set
                Me.listaImpuestosDeduccionesField = value
                Me.RaisePropertyChanged("listaImpuestosDeducciones")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property pagable() As Boolean
            Get
                Return Me.pagableField
            End Get
            Set
                Me.pagableField = value
                Me.RaisePropertyChanged("pagable")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property pagableSpecified() As Boolean
            Get
                Return Me.pagableFieldSpecified
            End Get
            Set
                Me.pagableFieldSpecified = value
                Me.RaisePropertyChanged("pagableSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property valorUnitario() As Decimal
            Get
                Return Me.valorUnitarioField
            End Get
            Set
                Me.valorUnitarioField = value
                Me.RaisePropertyChanged("valorUnitario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property valorUnitarioSpecified() As Boolean
            Get
                Return Me.valorUnitarioFieldSpecified
            End Get
            Set
                Me.valorUnitarioFieldSpecified = value
                Me.RaisePropertyChanged("valorUnitarioSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class numeracionResolucionWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private desdeField As Long
        
        Private hastaField As Long
        
        Private prefijoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property desde() As Long
            Get
                Return Me.desdeField
            End Get
            Set
                Me.desdeField = value
                Me.RaisePropertyChanged("desde")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property hasta() As Long
            Get
                Return Me.hastaField
            End Get
            Set
                Me.hastaField = value
                Me.RaisePropertyChanged("hasta")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property prefijo() As String
            Get
                Return Me.prefijoField
            End Get
            Set
                Me.prefijoField = value
                Me.RaisePropertyChanged("prefijo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class prontoPagoWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private fechaField As String
        
        Private valorPagarField As Decimal
        
        Private valorPagarFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
                Me.RaisePropertyChanged("fecha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property valorPagar() As Decimal
            Get
                Return Me.valorPagarField
            End Get
            Set
                Me.valorPagarField = value
                Me.RaisePropertyChanged("valorPagar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property valorPagarSpecified() As Boolean
            Get
                Return Me.valorPagarFieldSpecified
            End Get
            Set
                Me.valorPagarFieldSpecified = value
                Me.RaisePropertyChanged("valorPagarSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class identificacionClienteWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoDocumentoDianField As Integer
        
        Private codigoDocumentoDianFieldSpecified As Boolean
        
        Private numeroIdentificacionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codigoDocumentoDian() As Integer
            Get
                Return Me.codigoDocumentoDianField
            End Get
            Set
                Me.codigoDocumentoDianField = value
                Me.RaisePropertyChanged("codigoDocumentoDian")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property codigoDocumentoDianSpecified() As Boolean
            Get
                Return Me.codigoDocumentoDianFieldSpecified
            End Get
            Set
                Me.codigoDocumentoDianFieldSpecified = value
                Me.RaisePropertyChanged("codigoDocumentoDianSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property numeroIdentificacion() As String
            Get
                Return Me.numeroIdentificacionField
            End Get
            Set
                Me.numeroIdentificacionField = value
                Me.RaisePropertyChanged("numeroIdentificacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(facturaElectronicaWS)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public MustInherit Class documentoElectronicoWS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private identificacionReceptorField As identificacionClienteWS
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property identificacionReceptor() As identificacionClienteWS
            Get
                Return Me.identificacionReceptorField
            End Get
            Set
                Me.identificacionReceptorField = value
                Me.RaisePropertyChanged("identificacionReceptor")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class facturaElectronicaWS
        Inherits documentoElectronicoWS
        
        Private codigoMonedaField As String
        
        Private descripcionField As String
        
        Private descuentosField() As prontoPagoWS
        
        Private fechaExpedicionField As String
        
        Private fechaVencimientoField As String
        
        Private icotermsField As String
        
        Private identificadorConsecutivoField As Long
        
        Private identificadorConsecutivoFieldSpecified As Boolean
        
        Private identificadorResolucionField As String
        
        Private mediosPagoField As String
        
        Private nombreSucursalField As String
        
        Private numeracionResolucionWSField As numeracionResolucionWS
        
        Private ordenCompraField As String
        
        Private perfilEmisionField As enumPerfilPersona
        
        Private perfilEmisionFieldSpecified As Boolean
        
        Private perfilUsuarioField As enumPerfilPersona
        
        Private perfilUsuarioFieldSpecified As Boolean
        
        Private productosField() As productoCertifacturaWS
        
        Private subtotalFacturaField As Decimal
        
        Private subtotalFacturaFieldSpecified As Boolean
        
        Private subtotalesImpuestosDeduccionField() As impuestoDeduccionWS
        
        Private tipoFacturaField As String
        
        Private totalAnticiposField As Decimal
        
        Private totalAnticiposFieldSpecified As Boolean
        
        Private totalDescuentosField As Decimal
        
        Private totalDescuentosFieldSpecified As Boolean
        
        Private totalFacturaField As Decimal
        
        Private totalFacturaFieldSpecified As Boolean
        
        Private totalOtrosCostosField As Decimal
        
        Private totalOtrosCostosFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codigoMoneda() As String
            Get
                Return Me.codigoMonedaField
            End Get
            Set
                Me.codigoMonedaField = value
                Me.RaisePropertyChanged("codigoMoneda")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("descripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2),  _
         System.Xml.Serialization.XmlArrayItemAttribute("prontoPago", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descuentos() As prontoPagoWS()
            Get
                Return Me.descuentosField
            End Get
            Set
                Me.descuentosField = value
                Me.RaisePropertyChanged("descuentos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property fechaExpedicion() As String
            Get
                Return Me.fechaExpedicionField
            End Get
            Set
                Me.fechaExpedicionField = value
                Me.RaisePropertyChanged("fechaExpedicion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property fechaVencimiento() As String
            Get
                Return Me.fechaVencimientoField
            End Get
            Set
                Me.fechaVencimientoField = value
                Me.RaisePropertyChanged("fechaVencimiento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property icoterms() As String
            Get
                Return Me.icotermsField
            End Get
            Set
                Me.icotermsField = value
                Me.RaisePropertyChanged("icoterms")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property identificadorConsecutivo() As Long
            Get
                Return Me.identificadorConsecutivoField
            End Get
            Set
                Me.identificadorConsecutivoField = value
                Me.RaisePropertyChanged("identificadorConsecutivo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property identificadorConsecutivoSpecified() As Boolean
            Get
                Return Me.identificadorConsecutivoFieldSpecified
            End Get
            Set
                Me.identificadorConsecutivoFieldSpecified = value
                Me.RaisePropertyChanged("identificadorConsecutivoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property identificadorResolucion() As String
            Get
                Return Me.identificadorResolucionField
            End Get
            Set
                Me.identificadorResolucionField = value
                Me.RaisePropertyChanged("identificadorResolucion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property mediosPago() As String
            Get
                Return Me.mediosPagoField
            End Get
            Set
                Me.mediosPagoField = value
                Me.RaisePropertyChanged("mediosPago")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property nombreSucursal() As String
            Get
                Return Me.nombreSucursalField
            End Get
            Set
                Me.nombreSucursalField = value
                Me.RaisePropertyChanged("nombreSucursal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property numeracionResolucionWS() As numeracionResolucionWS
            Get
                Return Me.numeracionResolucionWSField
            End Get
            Set
                Me.numeracionResolucionWSField = value
                Me.RaisePropertyChanged("numeracionResolucionWS")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property ordenCompra() As String
            Get
                Return Me.ordenCompraField
            End Get
            Set
                Me.ordenCompraField = value
                Me.RaisePropertyChanged("ordenCompra")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property perfilEmision() As enumPerfilPersona
            Get
                Return Me.perfilEmisionField
            End Get
            Set
                Me.perfilEmisionField = value
                Me.RaisePropertyChanged("perfilEmision")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property perfilEmisionSpecified() As Boolean
            Get
                Return Me.perfilEmisionFieldSpecified
            End Get
            Set
                Me.perfilEmisionFieldSpecified = value
                Me.RaisePropertyChanged("perfilEmisionSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property perfilUsuario() As enumPerfilPersona
            Get
                Return Me.perfilUsuarioField
            End Get
            Set
                Me.perfilUsuarioField = value
                Me.RaisePropertyChanged("perfilUsuario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property perfilUsuarioSpecified() As Boolean
            Get
                Return Me.perfilUsuarioFieldSpecified
            End Get
            Set
                Me.perfilUsuarioFieldSpecified = value
                Me.RaisePropertyChanged("perfilUsuarioSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("productos", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=14)>  _
        Public Property productos() As productoCertifacturaWS()
            Get
                Return Me.productosField
            End Get
            Set
                Me.productosField = value
                Me.RaisePropertyChanged("productos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=15)>  _
        Public Property subtotalFactura() As Decimal
            Get
                Return Me.subtotalFacturaField
            End Get
            Set
                Me.subtotalFacturaField = value
                Me.RaisePropertyChanged("subtotalFactura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property subtotalFacturaSpecified() As Boolean
            Get
                Return Me.subtotalFacturaFieldSpecified
            End Get
            Set
                Me.subtotalFacturaFieldSpecified = value
                Me.RaisePropertyChanged("subtotalFacturaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("subtotalesImpuestosDeduccion", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=16)>  _
        Public Property subtotalesImpuestosDeduccion() As impuestoDeduccionWS()
            Get
                Return Me.subtotalesImpuestosDeduccionField
            End Get
            Set
                Me.subtotalesImpuestosDeduccionField = value
                Me.RaisePropertyChanged("subtotalesImpuestosDeduccion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=17)>  _
        Public Property tipoFactura() As String
            Get
                Return Me.tipoFacturaField
            End Get
            Set
                Me.tipoFacturaField = value
                Me.RaisePropertyChanged("tipoFactura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=18)>  _
        Public Property totalAnticipos() As Decimal
            Get
                Return Me.totalAnticiposField
            End Get
            Set
                Me.totalAnticiposField = value
                Me.RaisePropertyChanged("totalAnticipos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property totalAnticiposSpecified() As Boolean
            Get
                Return Me.totalAnticiposFieldSpecified
            End Get
            Set
                Me.totalAnticiposFieldSpecified = value
                Me.RaisePropertyChanged("totalAnticiposSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=19)>  _
        Public Property totalDescuentos() As Decimal
            Get
                Return Me.totalDescuentosField
            End Get
            Set
                Me.totalDescuentosField = value
                Me.RaisePropertyChanged("totalDescuentos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property totalDescuentosSpecified() As Boolean
            Get
                Return Me.totalDescuentosFieldSpecified
            End Get
            Set
                Me.totalDescuentosFieldSpecified = value
                Me.RaisePropertyChanged("totalDescuentosSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=20)>  _
        Public Property totalFactura() As Decimal
            Get
                Return Me.totalFacturaField
            End Get
            Set
                Me.totalFacturaField = value
                Me.RaisePropertyChanged("totalFactura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property totalFacturaSpecified() As Boolean
            Get
                Return Me.totalFacturaFieldSpecified
            End Get
            Set
                Me.totalFacturaFieldSpecified = value
                Me.RaisePropertyChanged("totalFacturaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=21)>  _
        Public Property totalOtrosCostos() As Decimal
            Get
                Return Me.totalOtrosCostosField
            End Get
            Set
                Me.totalOtrosCostosField = value
                Me.RaisePropertyChanged("totalOtrosCostos")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property totalOtrosCostosSpecified() As Boolean
            Get
                Return Me.totalOtrosCostosFieldSpecified
            End Get
            Set
                Me.totalOtrosCostosFieldSpecified = value
                Me.RaisePropertyChanged("totalOtrosCostosSpecified")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Public Enum enumPerfilPersona
        
        '''<remarks/>
        CLIENTE
        
        '''<remarks/>
        ADQUIRIENTE
        
        '''<remarks/>
        PROVEEDOR
        
        '''<remarks/>
        PLATAFORMA
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class ExcepcionServiciosNegocio
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private campoField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property campo() As String
            Get
                Return Me.campoField
            End Get
            Set
                Me.campoField = value
                Me.RaisePropertyChanged("campo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("mensaje")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/")>  _
    Partial Public Class ExcepcionServicios
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private campoField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=1)>  _
        Public Property campo() As String
            Get
                Return Me.campoField
            End Get
            Set
                Me.campoField = value
                Me.RaisePropertyChanged("campo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=2)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("mensaje")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/", ConfigurationName:="wsFact.IServiciosEmitirFacturaElectronica")>  _
    Public Interface IServiciosEmitirFacturaElectronica
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(wsFact.ExcepcionServiciosTecnica), Action:="", Name:="ExcepcionServiciosTecnica"),  _
         System.ServiceModel.FaultContractAttribute(GetType(wsFact.ExcepcionServiciosNegocio), Action:="", Name:="ExcepcionServiciosNegocio"),  _
         System.ServiceModel.FaultContractAttribute(GetType(wsFact.ExcepcionServicios), Action:="", Name:="ExcepcionServicios"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(documentoElectronicoWS))>  _
        Function crearFacturaElectronicaConAdjuntos(ByVal request As wsFact.crearFacturaElectronicaConAdjuntos) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> wsFact.crearFacturaElectronicaConAdjuntosResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function crearFacturaElectronicaConAdjuntosAsync(ByVal request As wsFact.crearFacturaElectronicaConAdjuntos) As System.Threading.Tasks.Task(Of wsFact.crearFacturaElectronicaConAdjuntosResponse)
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(wsFact.ExcepcionServiciosTecnica), Action:="", Name:="ExcepcionServiciosTecnica"),  _
         System.ServiceModel.FaultContractAttribute(GetType(wsFact.ExcepcionServiciosNegocio), Action:="", Name:="ExcepcionServiciosNegocio"),  _
         System.ServiceModel.FaultContractAttribute(GetType(wsFact.ExcepcionServicios), Action:="", Name:="ExcepcionServicios"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(documentoElectronicoWS))>  _
        Function crearFacturaElectronica(ByVal request As wsFact.crearFacturaElectronica) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> wsFact.crearFacturaElectronicaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function crearFacturaElectronicaAsync(ByVal request As wsFact.crearFacturaElectronica) As System.Threading.Tasks.Task(Of wsFact.crearFacturaElectronicaResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="crearFacturaElectronicaConAdjuntos", WrapperNamespace:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/", IsWrapped:=true)>  _
    Partial Public Class crearFacturaElectronicaConAdjuntos
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public facturaElectronicaCanonica As wsFact.facturaElectronicaWS
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public facturaEspecializada As wsFact.documentoPersonalizado
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal facturaElectronicaCanonica As wsFact.facturaElectronicaWS, ByVal facturaEspecializada As wsFact.documentoPersonalizado)
            MyBase.New
            Me.facturaElectronicaCanonica = facturaElectronicaCanonica
            Me.facturaEspecializada = facturaEspecializada
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="crearFacturaElectronicaConAdjuntosResponse", WrapperNamespace:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/", IsWrapped:=true)>  _
    Partial Public Class crearFacturaElectronicaConAdjuntosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="crearFacturaElectronica", WrapperNamespace:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/", IsWrapped:=true)>  _
    Partial Public Class crearFacturaElectronica
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public facturaElectronicaCanonica As wsFact.facturaElectronicaWS
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public facturaEspecializada As wsFact.documentoPersonalizado
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal facturaElectronicaCanonica As wsFact.facturaElectronicaWS, ByVal facturaEspecializada As wsFact.documentoPersonalizado)
            MyBase.New
            Me.facturaElectronicaCanonica = facturaElectronicaCanonica
            Me.facturaEspecializada = facturaEspecializada
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="crearFacturaElectronicaResponse", WrapperNamespace:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/", IsWrapped:=true)>  _
    Partial Public Class crearFacturaElectronicaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://contrato.factura.webservices.servicios.certifactura.certicamara.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServiciosEmitirFacturaElectronicaChannel
        Inherits wsFact.IServiciosEmitirFacturaElectronica, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiciosEmitirFacturaElectronicaClient
        Inherits System.ServiceModel.ClientBase(Of wsFact.IServiciosEmitirFacturaElectronica)
        Implements wsFact.IServiciosEmitirFacturaElectronica
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsFact_IServiciosEmitirFacturaElectronica_crearFacturaElectronicaConAdjuntos(ByVal request As wsFact.crearFacturaElectronicaConAdjuntos) As wsFact.crearFacturaElectronicaConAdjuntosResponse Implements wsFact.IServiciosEmitirFacturaElectronica.crearFacturaElectronicaConAdjuntos
            Return MyBase.Channel.crearFacturaElectronicaConAdjuntos(request)
        End Function
        
        Public Function crearFacturaElectronicaConAdjuntos(ByVal facturaElectronicaCanonica As wsFact.facturaElectronicaWS, ByVal facturaEspecializada As wsFact.documentoPersonalizado) As String
            Dim inValue As wsFact.crearFacturaElectronicaConAdjuntos = New wsFact.crearFacturaElectronicaConAdjuntos()
            inValue.facturaElectronicaCanonica = facturaElectronicaCanonica
            inValue.facturaEspecializada = facturaEspecializada
            Dim retVal As wsFact.crearFacturaElectronicaConAdjuntosResponse = CType(Me,wsFact.IServiciosEmitirFacturaElectronica).crearFacturaElectronicaConAdjuntos(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsFact_IServiciosEmitirFacturaElectronica_crearFacturaElectronicaConAdjuntosAsync(ByVal request As wsFact.crearFacturaElectronicaConAdjuntos) As System.Threading.Tasks.Task(Of wsFact.crearFacturaElectronicaConAdjuntosResponse) Implements wsFact.IServiciosEmitirFacturaElectronica.crearFacturaElectronicaConAdjuntosAsync
            Return MyBase.Channel.crearFacturaElectronicaConAdjuntosAsync(request)
        End Function
        
        Public Function crearFacturaElectronicaConAdjuntosAsync(ByVal facturaElectronicaCanonica As wsFact.facturaElectronicaWS, ByVal facturaEspecializada As wsFact.documentoPersonalizado) As System.Threading.Tasks.Task(Of wsFact.crearFacturaElectronicaConAdjuntosResponse)
            Dim inValue As wsFact.crearFacturaElectronicaConAdjuntos = New wsFact.crearFacturaElectronicaConAdjuntos()
            inValue.facturaElectronicaCanonica = facturaElectronicaCanonica
            inValue.facturaEspecializada = facturaEspecializada
            Return CType(Me,wsFact.IServiciosEmitirFacturaElectronica).crearFacturaElectronicaConAdjuntosAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsFact_IServiciosEmitirFacturaElectronica_crearFacturaElectronica(ByVal request As wsFact.crearFacturaElectronica) As wsFact.crearFacturaElectronicaResponse Implements wsFact.IServiciosEmitirFacturaElectronica.crearFacturaElectronica
            Return MyBase.Channel.crearFacturaElectronica(request)
        End Function
        
        Public Function crearFacturaElectronica(ByVal facturaElectronicaCanonica As wsFact.facturaElectronicaWS, ByVal facturaEspecializada As wsFact.documentoPersonalizado) As String
            Dim inValue As wsFact.crearFacturaElectronica = New wsFact.crearFacturaElectronica()
            inValue.facturaElectronicaCanonica = facturaElectronicaCanonica
            inValue.facturaEspecializada = facturaEspecializada
            Dim retVal As wsFact.crearFacturaElectronicaResponse = CType(Me,wsFact.IServiciosEmitirFacturaElectronica).crearFacturaElectronica(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsFact_IServiciosEmitirFacturaElectronica_crearFacturaElectronicaAsync(ByVal request As wsFact.crearFacturaElectronica) As System.Threading.Tasks.Task(Of wsFact.crearFacturaElectronicaResponse) Implements wsFact.IServiciosEmitirFacturaElectronica.crearFacturaElectronicaAsync
            Return MyBase.Channel.crearFacturaElectronicaAsync(request)
        End Function
        
        Public Function crearFacturaElectronicaAsync(ByVal facturaElectronicaCanonica As wsFact.facturaElectronicaWS, ByVal facturaEspecializada As wsFact.documentoPersonalizado) As System.Threading.Tasks.Task(Of wsFact.crearFacturaElectronicaResponse)
            Dim inValue As wsFact.crearFacturaElectronica = New wsFact.crearFacturaElectronica()
            inValue.facturaElectronicaCanonica = facturaElectronicaCanonica
            inValue.facturaEspecializada = facturaEspecializada
            Return CType(Me,wsFact.IServiciosEmitirFacturaElectronica).crearFacturaElectronicaAsync(inValue)
        End Function
    End Class
End Namespace
